services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./migrations:/docker-entrypoint-initdb.d
    networks:
      - quiz-net

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    environment:
      DB_DSN: "root:root@tcp(db:3306)/quiz?parseTime=true&multiStatements=true"
      JWT_SECRET: "devsecret"
    depends_on:
      - db
    ports:
      - "8081:${API_PORT}"
    networks:
      - quiz-net
    restart: on-failure

  # web:
  #   build:
  #     context: ./web
  #     dockerfile: Dockerfile
  #   environment:
  #     # Inside the web container, the api service is reachable at http://api:8080
  #     NEXT_PUBLIC_API_URL: "http://api:${API_PORT}"
  #   depends_on:
  #     - api
  #   ports:
  #     - "${WEB_PORT}:3000"
  #   networks:
  #     - quiz-net

volumes:
  db_data:

networks:
  quiz-net:
    driver: bridge
