// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql"
	"encoding/json"
)

type Card struct {
	ID            int64           `json:"id"`
	Question      string          `json:"question"`
	CorrectAnswer string          `json:"correct_answer"`
	WrongAnswers  json.RawMessage `json:"wrong_answers"`
	CreatedAt     sql.NullTime    `json:"created_at"`
}

type Quiz struct {
	ID         int64         `json:"id"`
	UserID     int64         `json:"user_id"`
	StartedAt  sql.NullTime  `json:"started_at"`
	FinishedAt sql.NullTime  `json:"finished_at"`
	Score      sql.NullInt32 `json:"score"`
}

type QuizAnswer struct {
	ID         int64        `json:"id"`
	QuizID     int64        `json:"quiz_id"`
	CardID     int64        `json:"card_id"`
	AnswerText string       `json:"answer_text"`
	IsCorrect  bool         `json:"is_correct"`
	AnsweredAt sql.NullTime `json:"answered_at"`
}

type QuizQuestion struct {
	ID       int64 `json:"id"`
	QuizID   int64 `json:"quiz_id"`
	CardID   int64 `json:"card_id"`
	Position int32 `json:"position"`
}

type User struct {
	ID           int64        `json:"id"`
	Email        string       `json:"email"`
	PasswordHash []byte       `json:"password_hash"`
	CreatedAt    sql.NullTime `json:"created_at"`
}
