// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: queries.sql

package db

import (
	"context"
	"database/sql"
	"encoding/json"
)

const addQuizQuestion = `-- name: AddQuizQuestion :exec
INSERT INTO quiz_questions(quiz_id, card_id, position) VALUES ($1, $2, $3)
`

type AddQuizQuestionParams struct {
	QuizID   int64 `json:"quiz_id"`
	CardID   int64 `json:"card_id"`
	Position int32 `json:"position"`
}

func (q *Queries) AddQuizQuestion(ctx context.Context, arg AddQuizQuestionParams) error {
	_, err := q.db.ExecContext(ctx, addQuizQuestion, arg.QuizID, arg.CardID, arg.Position)
	return err
}

const createCard = `-- name: CreateCard :exec
INSERT INTO cards(question, correct_answer, wrong_answers) VALUES ($1, $2, $3)
`

type CreateCardParams struct {
	Question      string          `json:"question"`
	CorrectAnswer string          `json:"correct_answer"`
	WrongAnswers  json.RawMessage `json:"wrong_answers"`
}

func (q *Queries) CreateCard(ctx context.Context, arg CreateCardParams) error {
	_, err := q.db.ExecContext(ctx, createCard, arg.Question, arg.CorrectAnswer, arg.WrongAnswers)
	return err
}

const createUser = `-- name: CreateUser :exec
INSERT INTO users(email, password_hash) VALUES ($1, $2)
`

type CreateUserParams struct {
	Email        string `json:"email"`
	PasswordHash []byte `json:"password_hash"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.ExecContext(ctx, createUser, arg.Email, arg.PasswordHash)
	return err
}

const deleteCard = `-- name: DeleteCard :exec
DELETE FROM cards WHERE id = $1
`

func (q *Queries) DeleteCard(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteCard, id)
	return err
}

const getCorrectAnswer = `-- name: GetCorrectAnswer :one
SELECT correct_answer FROM cards WHERE id = $1
`

func (q *Queries) GetCorrectAnswer(ctx context.Context, id int64) (string, error) {
	row := q.db.QueryRowContext(ctx, getCorrectAnswer, id)
	var correct_answer string
	err := row.Scan(&correct_answer)
	return correct_answer, err
}

const getQuiz = `-- name: GetQuiz :one
SELECT user_id, score, started_at, finished_at FROM quizzes WHERE id = $1
`

type GetQuizRow struct {
	UserID     int64         `json:"user_id"`
	Score      sql.NullInt32 `json:"score"`
	StartedAt  sql.NullTime  `json:"started_at"`
	FinishedAt sql.NullTime  `json:"finished_at"`
}

func (q *Queries) GetQuiz(ctx context.Context, id int64) (GetQuizRow, error) {
	row := q.db.QueryRowContext(ctx, getQuiz, id)
	var i GetQuizRow
	err := row.Scan(
		&i.UserID,
		&i.Score,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, password_hash FROM users WHERE email = $1
`

type GetUserByEmailRow struct {
	ID           int64  `json:"id"`
	PasswordHash []byte `json:"password_hash"`
}

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i GetUserByEmailRow
	err := row.Scan(&i.ID, &i.PasswordHash)
	return i, err
}

const listCards = `-- name: ListCards :many
SELECT id, question, correct_answer, wrong_answers FROM cards ORDER BY id DESC LIMIT 100
`

type ListCardsRow struct {
	ID            int64           `json:"id"`
	Question      string          `json:"question"`
	CorrectAnswer string          `json:"correct_answer"`
	WrongAnswers  json.RawMessage `json:"wrong_answers"`
}

func (q *Queries) ListCards(ctx context.Context) ([]ListCardsRow, error) {
	rows, err := q.db.QueryContext(ctx, listCards)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCardsRow
	for rows.Next() {
		var i ListCardsRow
		if err := rows.Scan(
			&i.ID,
			&i.Question,
			&i.CorrectAnswer,
			&i.WrongAnswers,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listQuizQuestions = `-- name: ListQuizQuestions :many
SELECT card_id, position FROM quiz_questions WHERE quiz_id = $1 ORDER BY position
`

type ListQuizQuestionsRow struct {
	CardID   int64 `json:"card_id"`
	Position int32 `json:"position"`
}

func (q *Queries) ListQuizQuestions(ctx context.Context, quizID int64) ([]ListQuizQuestionsRow, error) {
	rows, err := q.db.QueryContext(ctx, listQuizQuestions, quizID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListQuizQuestionsRow
	for rows.Next() {
		var i ListQuizQuestionsRow
		if err := rows.Scan(&i.CardID, &i.Position); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordAnswer = `-- name: RecordAnswer :exec
INSERT INTO quiz_answers(quiz_id, card_id, answer_text, is_correct) VALUES ($1, $2, $3, $4)
`

type RecordAnswerParams struct {
	QuizID     int64  `json:"quiz_id"`
	CardID     int64  `json:"card_id"`
	AnswerText string `json:"answer_text"`
	IsCorrect  bool   `json:"is_correct"`
}

func (q *Queries) RecordAnswer(ctx context.Context, arg RecordAnswerParams) error {
	_, err := q.db.ExecContext(ctx, recordAnswer,
		arg.QuizID,
		arg.CardID,
		arg.AnswerText,
		arg.IsCorrect,
	)
	return err
}

const selectRandomCards = `-- name: SelectRandomCards :many
SELECT id FROM cards ORDER BY RANDOM() LIMIT $1
`

func (q *Queries) SelectRandomCards(ctx context.Context, limit int32) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, selectRandomCards, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const startQuiz = `-- name: StartQuiz :one
INSERT INTO quizzes(user_id) VALUES ($1) RETURNING id
`

func (q *Queries) StartQuiz(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, startQuiz, userID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const updateScore = `-- name: UpdateScore :exec
UPDATE quizzes SET score = score + 1 WHERE id = $1
`

func (q *Queries) UpdateScore(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, updateScore, id)
	return err
}
